# Generated by Django 5.0.1 on 2026-03-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recovery_email',
            field=models.EmailField(blank=True, help_text='Optional recovery email for password resets', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Full phone number with country code', max_length=20, null=True),
        ),
    ]
