# Generated by Django 5.0.1 on 2026-04-07 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_recovery_email_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Nepal mobile number (10 digits)', max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='invalid_nepal_phone', message='Invalid Nepal mobile number. Must be 10 digits starting with valid NTC/Ncell prefix (984-986, 974-976, 980-982, 970).', regex='^(98[0-2456]|97[0-6])\\d{7}$')]),
        ),
    ]
