# Generated by Django 5.0.1 on 2026-04-11 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Mobile number (10 digits, starts with 98 or 97)', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='KhaltiPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200, unique=True)),
                ('amount', models.IntegerField(help_text='Amount in paisa (1 NPR = 100 paisa)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khalti_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'khalti_payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
