# Generated by Django 5.0.1 on 2026-04-16 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_resolved',
            field=models.BooleanField(default=False, help_text='Item marked as resolved/returned'),
        ),
        migrations.AddField(
            model_name='item',
            name='reward_paid',
            field=models.BooleanField(default=False, help_text='Reward payment completed via Khalti'),
        ),
    ]
