# Generated by Django 5.0.1 on 2026-04-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_is_resolved_item_reward_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='contact_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='claim',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='claim',
            name='proof_details',
            field=models.TextField(blank=True, default='', help_text='Provide text details proving ownership'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='message',
            field=models.TextField(help_text='Message to the owner explaining how you found the item or why it belongs to you'),
        ),
    ]
