# Generated by Django 5.0.1 on 2026-04-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemrequest',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='redeemrequest',
            name='payout_reference',
            field=models.CharField(blank=True, default='', help_text="User's Khalti number or preferred payment method info", max_length=200),
        ),
    ]
